<img src="../Pierian-Data-Logo.PNG">
<br>
<strong><center>Copyright 2019. Created by Jose Marcial Portilla.</center></strong>

# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [47]:
# CODE HERE

import torch
import numpy as np

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [51]:
# CODE HERE
np.random.seed(42)
torch.manual_seed(42);

### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [52]:
# CODE HERE

arr = np.random.randint(0, 6, size=(6))
arr

array([3, 4, 2, 4, 4, 1])

In [33]:
# DON'T WRITE HERE

### 4. Create a tensor "x" from the array above

In [53]:
# CODE HERE
x = torch.tensor(arr)
x

tensor([3, 4, 2, 4, 4, 1])

In [35]:
# DON'T WRITE HERE

### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [54]:
# CODE HERE

x = x.type(torch.int32)
x

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

In [37]:
# DON'T WRITE HERE

### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [56]:
# CODE HERE

x = x.reshape(3, 2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]], dtype=torch.int32)

In [39]:
# DON'T WRITE HERE

### 7. Return the right-hand column of tensor x

In [57]:
# CODE HERE

x[:, 1:]

tensor([[4],
        [4],
        [1]], dtype=torch.int32)

In [41]:
# DON'T WRITE HERE

### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [58]:
# CODE HERE

x ** 2

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]], dtype=torch.int32)

In [43]:
# DON'T WRITE HERE

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [59]:
# CODE HERE

y = torch.randint(0, 6, size=(2,3))
y

tensor([[0, 5, 4],
        [4, 0, 5]])

In [45]:
# DON'T WRITE HERE

### 10. Find the matrix product of x and y

In [62]:
# CODE HERE
x

tensor([[3, 4],
        [2, 4],
        [4, 1]], dtype=torch.int32)

In [66]:
y = torch.randint(0,5,(2,3))
y

tensor([[0, 4, 1],
        [2, 0, 0]])

In [64]:
print(x.mm(y))

RuntimeError: Expected object of scalar type Int but got scalar type Long for argument #2 'mat2'

In [10]:
# DON'T WRITE HERE

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Great job!