In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(6).reshape(3,2)

In [3]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
type(x[1,1])

torch.Tensor

In [5]:
x[:, 1]

tensor([1, 3, 5])

In [6]:
x[:, 1:] # slicing

tensor([[1],
        [3],
        [5]])

In [7]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x.view(2,5) 

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
z = x.view(2,5)

In [13]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
x[0] = 9999

In [15]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [17]:
z # linked

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [22]:
x = torch.arange(10)
x.shape

torch.Size([10])

In [23]:
# -1 INFER what the 2nd dimension is
x.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
a = torch.tensor([1., 2., 3.])

In [27]:
b = torch.tensor([4., 5., 6.])

In [28]:
a + b

tensor([5., 7., 9.])

In [30]:
torch.add(a,b) # + calls this

tensor([5., 7., 9.])

In [35]:
a.mul_(b) # underscore perfoms action inplace

#a = a * b

tensor([ 16.,  50., 108.])

In [34]:
a

tensor([ 4., 10., 18.])

In [36]:
### Matrix multiplication

In [37]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

In [39]:
a * b # element wise

tensor([ 4., 10., 18.])

In [41]:
a.dot(b) # dot product

tensor(32.)

In [42]:
a @ b # dot product

tensor(32.)

In [43]:
a = torch.tensor([[0, 2, 4],[1,3,5]])
b = torch.tensor([[6,7], [8,9], [10,11]])

In [44]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [45]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [46]:
a.shape

torch.Size([2, 3])

In [47]:
b.shape

torch.Size([3, 2])

In [48]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [49]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [57]:
x = torch.tensor([2.,3.,4.,5.])
x

tensor([2., 3., 4., 5.])

In [58]:
x.norm()

tensor(7.3485)