In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [4]:
arr  = np.array([1,2,3,4,5])

In [5]:
arr.dtype

dtype('int64')

In [7]:
x = torch.from_numpy(arr)

In [8]:
type(x)

torch.Tensor

In [9]:
torch.as_tensor(arr) # only works with numpy arrays

tensor([1, 2, 3, 4, 5])

In [10]:
x

tensor([1, 2, 3, 4, 5])

In [11]:
x.dtype

torch.int64

In [18]:
arr2d = np.arange(0.0, 12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [19]:
arr2d = arr2d.reshape(4, 3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [20]:
x2 = torch.from_numpy(arr2d)

In [21]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [22]:
x

tensor([1, 2, 3, 4, 5])

In [25]:
arr[0] = 99

In [27]:
x # direct link to numpy

tensor([99,  2,  3,  4,  5])

In [28]:
my_arr = np.arange(0, 10)

In [29]:
my_tensor = torch.tensor(my_arr)

In [30]:
my_other_tensor = torch.from_numpy(my_arr)

In [32]:
my_arr[0] = 9999

In [33]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [35]:
new_arr = np.array([1,2,3])

In [39]:
torch.Tensor(new_arr).dtype #torch.Tensor shorthand for torch.FloatTensor

torch.float32

In [42]:
torch.empty(4,2) # placeholder

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [44]:
torch.zeros(4, 5, dtype=torch.int64)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [46]:
torch.arange(0, 18, 2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [48]:
torch.linspace(0, 18, 12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [49]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [50]:
my_tensor = torch.tensor([1,2,3])

In [51]:
my_tensor.dtype

torch.int64

In [54]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [55]:
torch.rand(4, 3) # Uniform distribution

tensor([[0.6320, 0.2204, 0.3748],
        [0.0605, 0.1571, 0.8344],
        [0.0207, 0.5631, 0.2037],
        [0.5703, 0.6058, 0.6311]])

In [56]:
torch.randn(4, 3) # Standard normal dist

tensor([[ 1.3631, -0.7354, -0.9290],
        [ 0.0987, -0.0837, -0.3080],
        [ 1.7904, -0.7520, -2.3668],
        [-0.0643,  2.1213,  2.0768]])

In [58]:
torch.randint(low=0, high=11, size=(5,5)) #high is exclusive

tensor([[ 8,  4,  8,  5,  3],
        [ 6,  8,  4,  6,  7],
        [ 8,  2,  9,  1,  6],
        [10,  5,  6,  2,  4],
        [ 8,  9,  2,  5,  7]])

In [60]:
x = torch.zeros(2, 5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [61]:
torch.rand_like(x) # uses shape of x

tensor([[0.1398, 0.5310, 0.8441, 0.2722, 0.4867],
        [0.9149, 0.2951, 0.2836, 0.6139, 0.8412]])

In [62]:
torch.randn_like(x)
torch.randint_like(x, low=0, high=11)

tensor([[2., 9., 8., 8., 8.],
        [1., 9., 5., 6., 2.]])

In [66]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [65]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])